#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace INVENTORY.Data
{
    /// <summary>
    /// The class representing the dbo.HtNguoiDungVaiTro table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.HtNguoiDungVaiTro")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(INVENTORY.Data.HtNguoiDungVaiTro.Metadata))]
    [System.Data.Services.Common.DataServiceKey("Id")]
    [System.Diagnostics.DebuggerDisplay("Id: {Id}")]
    public partial class HtNguoiDungVaiTro
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="HtNguoiDungVaiTro"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static HtNguoiDungVaiTro()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="HtNguoiDungVaiTro"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public HtNguoiDungVaiTro()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            _khoHangDmKhoHang = default(System.Data.Linq.EntityRef<DmKhoHang>);
            _nguoiDungHtNguoiDung = default(System.Data.Linq.EntityRef<HtNguoiDung>);
            _vaiTroHtVaiTro = default(System.Data.Linq.EntityRef<HtVaiTro>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _id = default(int);

        /// <summary>
        /// Gets the Id column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Id", Storage = "_id", DbType = "int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    SendPropertyChanging("Id");
                    _id = value;
                    SendPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _idNguoiDung;

        /// <summary>
        /// Gets or sets the IdNguoiDung column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdNguoiDung", Storage = "_idNguoiDung", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int IdNguoiDung
        {
            get { return _idNguoiDung; }
            set
            {
                if (_idNguoiDung != value)
                {
                    if (_nguoiDungHtNguoiDung.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdNguoiDungChanging(value);
                    SendPropertyChanging("IdNguoiDung");
                    _idNguoiDung = value;
                    SendPropertyChanged("IdNguoiDung");
                    OnIdNguoiDungChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _idVaiTro;

        /// <summary>
        /// Gets or sets the IdVaiTro column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdVaiTro", Storage = "_idVaiTro", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int IdVaiTro
        {
            get { return _idVaiTro; }
            set
            {
                if (_idVaiTro != value)
                {
                    if (_vaiTroHtVaiTro.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdVaiTroChanging(value);
                    SendPropertyChanging("IdVaiTro");
                    _idVaiTro = value;
                    SendPropertyChanged("IdVaiTro");
                    OnIdVaiTroChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _idKhoHang;

        /// <summary>
        /// Gets or sets the IdKhoHang column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdKhoHang", Storage = "_idKhoHang", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int IdKhoHang
        {
            get { return _idKhoHang; }
            set
            {
                if (_idKhoHang != value)
                {
                    if (_khoHangDmKhoHang.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdKhoHangChanging(value);
                    SendPropertyChanging("IdKhoHang");
                    _idKhoHang = value;
                    SendPropertyChanged("IdKhoHang");
                    OnIdKhoHangChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool _macDinh;

        /// <summary>
        /// Gets or sets the MacDinh column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "MacDinh", Storage = "_macDinh", DbType = "bit NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public bool MacDinh
        {
            get { return _macDinh; }
            set
            {
                if (_macDinh != value)
                {
                    OnMacDinhChanging(value);
                    SendPropertyChanging("MacDinh");
                    _macDinh = value;
                    SendPropertyChanged("MacDinh");
                    OnMacDinhChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<DmKhoHang> _khoHangDmKhoHang;

        /// <summary>
        /// Gets or sets the <see cref="DmKhoHang"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "DmKhoHang_HtNguoiDungVaiTro", Storage = "_khoHangDmKhoHang", ThisKey = "IdKhoHang", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 6, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public DmKhoHang KhoHangDmKhoHang
        {
            get { return (serializing && !_khoHangDmKhoHang.HasLoadedOrAssignedValue) ? null : _khoHangDmKhoHang.Entity; }
            set
            {
                DmKhoHang previousValue = _khoHangDmKhoHang.Entity;
                if (previousValue != value || _khoHangDmKhoHang.HasLoadedOrAssignedValue == false)
                {
                    OnKhoHangDmKhoHangChanging(value);
                    SendPropertyChanging("KhoHangDmKhoHang");
                    if (previousValue != null)
                    {
                        _khoHangDmKhoHang.Entity = null;
                        previousValue.KhoHangHtNguoiDungVaiTroList.Remove(this);
                    }
                    _khoHangDmKhoHang.Entity = value;
                    if (value != null)
                    {
                        value.KhoHangHtNguoiDungVaiTroList.Add(this);
                        _idKhoHang = value.Id;
                    }
                    else
                    {
                        _idKhoHang = default(int);
                    }
                    SendPropertyChanged("KhoHangDmKhoHang");
                    OnKhoHangDmKhoHangChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<HtNguoiDung> _nguoiDungHtNguoiDung;

        /// <summary>
        /// Gets or sets the <see cref="HtNguoiDung"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "HtNguoiDung_HtNguoiDungVaiTro", Storage = "_nguoiDungHtNguoiDung", ThisKey = "IdNguoiDung", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 7, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public HtNguoiDung NguoiDungHtNguoiDung
        {
            get { return (serializing && !_nguoiDungHtNguoiDung.HasLoadedOrAssignedValue) ? null : _nguoiDungHtNguoiDung.Entity; }
            set
            {
                HtNguoiDung previousValue = _nguoiDungHtNguoiDung.Entity;
                if (previousValue != value || _nguoiDungHtNguoiDung.HasLoadedOrAssignedValue == false)
                {
                    OnNguoiDungHtNguoiDungChanging(value);
                    SendPropertyChanging("NguoiDungHtNguoiDung");
                    if (previousValue != null)
                    {
                        _nguoiDungHtNguoiDung.Entity = null;
                        previousValue.NguoiDungHtNguoiDungVaiTroList.Remove(this);
                    }
                    _nguoiDungHtNguoiDung.Entity = value;
                    if (value != null)
                    {
                        value.NguoiDungHtNguoiDungVaiTroList.Add(this);
                        _idNguoiDung = value.Id;
                    }
                    else
                    {
                        _idNguoiDung = default(int);
                    }
                    SendPropertyChanged("NguoiDungHtNguoiDung");
                    OnNguoiDungHtNguoiDungChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<HtVaiTro> _vaiTroHtVaiTro;

        /// <summary>
        /// Gets or sets the <see cref="HtVaiTro"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "HtVaiTro_HtNguoiDungVaiTro", Storage = "_vaiTroHtVaiTro", ThisKey = "IdVaiTro", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 8, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public HtVaiTro VaiTroHtVaiTro
        {
            get { return (serializing && !_vaiTroHtVaiTro.HasLoadedOrAssignedValue) ? null : _vaiTroHtVaiTro.Entity; }
            set
            {
                HtVaiTro previousValue = _vaiTroHtVaiTro.Entity;
                if (previousValue != value || _vaiTroHtVaiTro.HasLoadedOrAssignedValue == false)
                {
                    OnVaiTroHtVaiTroChanging(value);
                    SendPropertyChanging("VaiTroHtVaiTro");
                    if (previousValue != null)
                    {
                        _vaiTroHtVaiTro.Entity = null;
                        previousValue.VaiTroHtNguoiDungVaiTroList.Remove(this);
                    }
                    _vaiTroHtVaiTro.Entity = value;
                    if (value != null)
                    {
                        value.VaiTroHtNguoiDungVaiTroList.Add(this);
                        _idVaiTro = value.Id;
                    }
                    else
                    {
                        _idVaiTro = default(int);
                    }
                    SendPropertyChanged("VaiTroHtVaiTro");
                    OnVaiTroHtVaiTroChanged();
                }
            }
        }
        
        
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="Id"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdChanging(int value);
        /// <summary>Called after <see cref="Id"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdChanged();
        /// <summary>Called when <see cref="IdNguoiDung"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdNguoiDungChanging(int value);
        /// <summary>Called after <see cref="IdNguoiDung"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdNguoiDungChanged();
        /// <summary>Called when <see cref="IdVaiTro"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdVaiTroChanging(int value);
        /// <summary>Called after <see cref="IdVaiTro"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdVaiTroChanged();
        /// <summary>Called when <see cref="IdKhoHang"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdKhoHangChanging(int value);
        /// <summary>Called after <see cref="IdKhoHang"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdKhoHangChanged();
        /// <summary>Called when <see cref="MacDinh"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnMacDinhChanging(bool value);
        /// <summary>Called after <see cref="MacDinh"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnMacDinhChanged();
        /// <summary>Called when <see cref="KhoHangDmKhoHang"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnKhoHangDmKhoHangChanging(DmKhoHang value);
        /// <summary>Called after <see cref="KhoHangDmKhoHang"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnKhoHangDmKhoHangChanged();
        /// <summary>Called when <see cref="NguoiDungHtNguoiDung"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnNguoiDungHtNguoiDungChanging(HtNguoiDung value);
        /// <summary>Called after <see cref="NguoiDungHtNguoiDung"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnNguoiDungHtNguoiDungChanged();
        /// <summary>Called when <see cref="VaiTroHtVaiTro"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnVaiTroHtVaiTroChanging(HtVaiTro value);
        /// <summary>Called after <see cref="VaiTroHtVaiTro"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnVaiTroHtVaiTroChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="HtNguoiDungVaiTro"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="HtNguoiDungVaiTro"/> instance.</param>
        /// <returns>An instance of <see cref="HtNguoiDungVaiTro"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static HtNguoiDungVaiTro FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(HtNguoiDungVaiTro));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as HtNguoiDungVaiTro;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="HtNguoiDungVaiTro"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="HtNguoiDungVaiTro"/> instance.</param>
        /// <returns>An instance of <see cref="HtNguoiDungVaiTro"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static HtNguoiDungVaiTro FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(HtNguoiDungVaiTro));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as HtNguoiDungVaiTro;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public HtNguoiDungVaiTro Clone()
        {
            return (HtNguoiDungVaiTro)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _khoHangDmKhoHang = Detach(_khoHangDmKhoHang);
            _nguoiDungHtNguoiDung = Detach(_nguoiDungHtNguoiDung);
            _vaiTroHtVaiTro = Detach(_vaiTroHtVaiTro);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
