#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace INVENTORY.Data
{
    /// <summary>
    /// The class representing the dbo.KhPhieuNhapNbCt table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.KhPhieuNhapNbCt")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(INVENTORY.Data.KhPhieuNhapNbCt.Metadata))]
    [System.Data.Services.Common.DataServiceKey("Id")]
    [System.Diagnostics.DebuggerDisplay("Id: {Id}")]
    public partial class KhPhieuNhapNbCt
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="KhPhieuNhapNbCt"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static KhPhieuNhapNbCt()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="KhPhieuNhapNbCt"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhPhieuNhapNbCt()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            _loaiVatTuDmLoaiVatTu = default(System.Data.Linq.EntityRef<DmLoaiVatTu>);
            _phieuNhapNbKhPhieuNhapNb = default(System.Data.Linq.EntityRef<KhPhieuNhapNb>);
            _sanPhamKhSanPham = default(System.Data.Linq.EntityRef<KhSanPham>);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _id;

        /// <summary>
        /// Gets or sets the Id column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Id", Storage = "_id", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    SendPropertyChanging("Id");
                    _id = value;
                    SendPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _idPhieuNhapNb;

        /// <summary>
        /// Gets or sets the IdPhieuNhapNb column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdPhieuNhapNb", Storage = "_idPhieuNhapNb", DbType = "uniqueidentifier NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid IdPhieuNhapNb
        {
            get { return _idPhieuNhapNb; }
            set
            {
                if (_idPhieuNhapNb != value)
                {
                    if (_phieuNhapNbKhPhieuNhapNb.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdPhieuNhapNbChanging(value);
                    SendPropertyChanging("IdPhieuNhapNb");
                    _idPhieuNhapNb = value;
                    SendPropertyChanged("IdPhieuNhapNb");
                    OnIdPhieuNhapNbChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _idLoaiVatTu;

        /// <summary>
        /// Gets or sets the IdLoaiVatTu column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdLoaiVatTu", Storage = "_idLoaiVatTu", DbType = "uniqueidentifier NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid IdLoaiVatTu
        {
            get { return _idLoaiVatTu; }
            set
            {
                if (_idLoaiVatTu != value)
                {
                    if (_loaiVatTuDmLoaiVatTu.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdLoaiVatTuChanging(value);
                    SendPropertyChanging("IdLoaiVatTu");
                    _idLoaiVatTu = value;
                    SendPropertyChanged("IdLoaiVatTu");
                    OnIdLoaiVatTuChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _idSanPham;

        /// <summary>
        /// Gets or sets the IdSanPham column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdSanPham", Storage = "_idSanPham", DbType = "uniqueidentifier NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid IdSanPham
        {
            get { return _idSanPham; }
            set
            {
                if (_idSanPham != value)
                {
                    if (_sanPhamKhSanPham.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdSanPhamChanging(value);
                    SendPropertyChanging("IdSanPham");
                    _idSanPham = value;
                    SendPropertyChanged("IdSanPham");
                    OnIdSanPhamChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _soLuong;

        /// <summary>
        /// Gets or sets the SoLuong column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "SoLuong", Storage = "_soLuong", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int SoLuong
        {
            get { return _soLuong; }
            set
            {
                if (_soLuong != value)
                {
                    OnSoLuongChanging(value);
                    SendPropertyChanging("SoLuong");
                    _soLuong = value;
                    SendPropertyChanged("SoLuong");
                    OnSoLuongChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _trangThai;

        /// <summary>
        /// Gets or sets the TrangThai column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "TrangThai", Storage = "_trangThai", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int TrangThai
        {
            get { return _trangThai; }
            set
            {
                if (_trangThai != value)
                {
                    OnTrangThaiChanging(value);
                    SendPropertyChanging("TrangThai");
                    _trangThai = value;
                    SendPropertyChanged("TrangThai");
                    OnTrangThaiChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _chuThich;

        /// <summary>
        /// Gets or sets the ChuThich column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ChuThich", Storage = "_chuThich", DbType = "nvarchar(300)")]
        [System.ComponentModel.DataAnnotations.StringLength(300)]
        [System.Runtime.Serialization.DataMember(Order = 7)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string ChuThich
        {
            get { return _chuThich; }
            set
            {
                if (_chuThich != value)
                {
                    OnChuThichChanging(value);
                    SendPropertyChanging("ChuThich");
                    _chuThich = value;
                    SendPropertyChanged("ChuThich");
                    OnChuThichChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<DmLoaiVatTu> _loaiVatTuDmLoaiVatTu;

        /// <summary>
        /// Gets or sets the <see cref="DmLoaiVatTu"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "DmLoaiVatTu_KhPhieuNhapNbCt", Storage = "_loaiVatTuDmLoaiVatTu", ThisKey = "IdLoaiVatTu", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 8, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public DmLoaiVatTu LoaiVatTuDmLoaiVatTu
        {
            get { return (serializing && !_loaiVatTuDmLoaiVatTu.HasLoadedOrAssignedValue) ? null : _loaiVatTuDmLoaiVatTu.Entity; }
            set
            {
                DmLoaiVatTu previousValue = _loaiVatTuDmLoaiVatTu.Entity;
                if (previousValue != value || _loaiVatTuDmLoaiVatTu.HasLoadedOrAssignedValue == false)
                {
                    OnLoaiVatTuDmLoaiVatTuChanging(value);
                    SendPropertyChanging("LoaiVatTuDmLoaiVatTu");
                    if (previousValue != null)
                    {
                        _loaiVatTuDmLoaiVatTu.Entity = null;
                        previousValue.LoaiVatTuKhPhieuNhapNbCtList.Remove(this);
                    }
                    _loaiVatTuDmLoaiVatTu.Entity = value;
                    if (value != null)
                    {
                        value.LoaiVatTuKhPhieuNhapNbCtList.Add(this);
                        _idLoaiVatTu = value.Id;
                    }
                    else
                    {
                        _idLoaiVatTu = default(System.Guid);
                    }
                    SendPropertyChanged("LoaiVatTuDmLoaiVatTu");
                    OnLoaiVatTuDmLoaiVatTuChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<KhPhieuNhapNb> _phieuNhapNbKhPhieuNhapNb;

        /// <summary>
        /// Gets or sets the <see cref="KhPhieuNhapNb"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "KhPhieuNhapNb_KhPhieuNhapNbCt", Storage = "_phieuNhapNbKhPhieuNhapNb", ThisKey = "IdPhieuNhapNb", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 9, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhPhieuNhapNb PhieuNhapNbKhPhieuNhapNb
        {
            get { return (serializing && !_phieuNhapNbKhPhieuNhapNb.HasLoadedOrAssignedValue) ? null : _phieuNhapNbKhPhieuNhapNb.Entity; }
            set
            {
                KhPhieuNhapNb previousValue = _phieuNhapNbKhPhieuNhapNb.Entity;
                if (previousValue != value || _phieuNhapNbKhPhieuNhapNb.HasLoadedOrAssignedValue == false)
                {
                    OnPhieuNhapNbKhPhieuNhapNbChanging(value);
                    SendPropertyChanging("PhieuNhapNbKhPhieuNhapNb");
                    if (previousValue != null)
                    {
                        _phieuNhapNbKhPhieuNhapNb.Entity = null;
                        previousValue.PhieuNhapNbKhPhieuNhapNbCtList.Remove(this);
                    }
                    _phieuNhapNbKhPhieuNhapNb.Entity = value;
                    if (value != null)
                    {
                        value.PhieuNhapNbKhPhieuNhapNbCtList.Add(this);
                        _idPhieuNhapNb = value.Id;
                    }
                    else
                    {
                        _idPhieuNhapNb = default(System.Guid);
                    }
                    SendPropertyChanged("PhieuNhapNbKhPhieuNhapNb");
                    OnPhieuNhapNbKhPhieuNhapNbChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<KhSanPham> _sanPhamKhSanPham;

        /// <summary>
        /// Gets or sets the <see cref="KhSanPham"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "KhSanPham_KhPhieuNhapNbCt", Storage = "_sanPhamKhSanPham", ThisKey = "IdSanPham", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 10, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhSanPham SanPhamKhSanPham
        {
            get { return (serializing && !_sanPhamKhSanPham.HasLoadedOrAssignedValue) ? null : _sanPhamKhSanPham.Entity; }
            set
            {
                KhSanPham previousValue = _sanPhamKhSanPham.Entity;
                if (previousValue != value || _sanPhamKhSanPham.HasLoadedOrAssignedValue == false)
                {
                    OnSanPhamKhSanPhamChanging(value);
                    SendPropertyChanging("SanPhamKhSanPham");
                    if (previousValue != null)
                    {
                        _sanPhamKhSanPham.Entity = null;
                        previousValue.SanPhamKhPhieuNhapNbCtList.Remove(this);
                    }
                    _sanPhamKhSanPham.Entity = value;
                    if (value != null)
                    {
                        value.SanPhamKhPhieuNhapNbCtList.Add(this);
                        _idSanPham = value.Id;
                    }
                    else
                    {
                        _idSanPham = default(System.Guid);
                    }
                    SendPropertyChanged("SanPhamKhSanPham");
                    OnSanPhamKhSanPhamChanged();
                }
            }
        }
        
        
        
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="Id"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdChanging(System.Guid value);
        /// <summary>Called after <see cref="Id"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdChanged();
        /// <summary>Called when <see cref="IdPhieuNhapNb"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdPhieuNhapNbChanging(System.Guid value);
        /// <summary>Called after <see cref="IdPhieuNhapNb"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdPhieuNhapNbChanged();
        /// <summary>Called when <see cref="IdLoaiVatTu"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdLoaiVatTuChanging(System.Guid value);
        /// <summary>Called after <see cref="IdLoaiVatTu"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdLoaiVatTuChanged();
        /// <summary>Called when <see cref="IdSanPham"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSanPhamChanging(System.Guid value);
        /// <summary>Called after <see cref="IdSanPham"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdSanPhamChanged();
        /// <summary>Called when <see cref="SoLuong"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnSoLuongChanging(int value);
        /// <summary>Called after <see cref="SoLuong"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnSoLuongChanged();
        /// <summary>Called when <see cref="TrangThai"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnTrangThaiChanging(int value);
        /// <summary>Called after <see cref="TrangThai"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnTrangThaiChanged();
        /// <summary>Called when <see cref="ChuThich"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChuThichChanging(string value);
        /// <summary>Called after <see cref="ChuThich"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChuThichChanged();
        /// <summary>Called when <see cref="LoaiVatTuDmLoaiVatTu"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaiVatTuDmLoaiVatTuChanging(DmLoaiVatTu value);
        /// <summary>Called after <see cref="LoaiVatTuDmLoaiVatTu"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaiVatTuDmLoaiVatTuChanged();
        /// <summary>Called when <see cref="PhieuNhapNbKhPhieuNhapNb"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnPhieuNhapNbKhPhieuNhapNbChanging(KhPhieuNhapNb value);
        /// <summary>Called after <see cref="PhieuNhapNbKhPhieuNhapNb"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnPhieuNhapNbKhPhieuNhapNbChanged();
        /// <summary>Called when <see cref="SanPhamKhSanPham"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnSanPhamKhSanPhamChanging(KhSanPham value);
        /// <summary>Called after <see cref="SanPhamKhSanPham"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnSanPhamKhSanPhamChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="KhPhieuNhapNbCt"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="KhPhieuNhapNbCt"/> instance.</param>
        /// <returns>An instance of <see cref="KhPhieuNhapNbCt"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static KhPhieuNhapNbCt FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(KhPhieuNhapNbCt));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as KhPhieuNhapNbCt;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="KhPhieuNhapNbCt"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="KhPhieuNhapNbCt"/> instance.</param>
        /// <returns>An instance of <see cref="KhPhieuNhapNbCt"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static KhPhieuNhapNbCt FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(KhPhieuNhapNbCt));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as KhPhieuNhapNbCt;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhPhieuNhapNbCt Clone()
        {
            return (KhPhieuNhapNbCt)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _loaiVatTuDmLoaiVatTu = Detach(_loaiVatTuDmLoaiVatTu);
            _phieuNhapNbKhPhieuNhapNb = Detach(_phieuNhapNbKhPhieuNhapNb);
            _sanPhamKhSanPham = Detach(_sanPhamKhSanPham);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
