#pragma warning disable 1591
#pragma warning disable 0414        
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Linq;

namespace INVENTORY.Data
{
    /// <summary>
    /// The class representing the dbo.KhPhieuXuatCt table.
    /// </summary>
    [System.Data.Linq.Mapping.Table(Name="dbo.KhPhieuXuatCt")]
    [System.Runtime.Serialization.DataContract(IsReference = true)]
    [System.ComponentModel.DataAnnotations.ScaffoldTable(true)]
    [System.ComponentModel.DataAnnotations.MetadataType(typeof(INVENTORY.Data.KhPhieuXuatCt.Metadata))]
    [System.Data.Services.Common.DataServiceKey("Id")]
    [System.Diagnostics.DebuggerDisplay("Id: {Id}")]
    public partial class KhPhieuXuatCt
        : LinqEntityBase, ICloneable 
    {
        #region Static Constructor
        /// <summary>
        /// Initializes the <see cref="KhPhieuXuatCt"/> class.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static KhPhieuXuatCt()
        {
            AddSharedRules();
        }
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="KhPhieuXuatCt"/> class.
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhPhieuXuatCt()
        {
            Initialize();
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void Initialize()
        {
            _loaiVatTuDmLoaiVatTu = default(System.Data.Linq.EntityRef<DmLoaiVatTu>);
            _phieuXuatKhPhieuXuat = default(System.Data.Linq.EntityRef<KhPhieuXuat>);
            _phieuXuatCtKhPhieuXuatSpList = new System.Data.Linq.EntitySet<KhPhieuXuatSp>(OnPhieuXuatCtKhPhieuXuatSpListAdd, OnPhieuXuatCtKhPhieuXuatSpListRemove);
            OnCreated();
        }
        #endregion

        #region Column Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _id;

        /// <summary>
        /// Gets or sets the Id column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "Id", Storage = "_id", DbType = "uniqueidentifier NOT NULL", IsPrimaryKey = true, CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 1)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    OnIdChanging(value);
                    SendPropertyChanging("Id");
                    _id = value;
                    SendPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _idPhieuXuat;

        /// <summary>
        /// Gets or sets the IdPhieuXuat column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdPhieuXuat", Storage = "_idPhieuXuat", DbType = "uniqueidentifier NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 2)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid IdPhieuXuat
        {
            get { return _idPhieuXuat; }
            set
            {
                if (_idPhieuXuat != value)
                {
                    if (_phieuXuatKhPhieuXuat.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdPhieuXuatChanging(value);
                    SendPropertyChanging("IdPhieuXuat");
                    _idPhieuXuat = value;
                    SendPropertyChanged("IdPhieuXuat");
                    OnIdPhieuXuatChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Guid _idLoaiVatTu;

        /// <summary>
        /// Gets or sets the IdLoaiVatTu column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "IdLoaiVatTu", Storage = "_idLoaiVatTu", DbType = "uniqueidentifier NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 3)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Guid IdLoaiVatTu
        {
            get { return _idLoaiVatTu; }
            set
            {
                if (_idLoaiVatTu != value)
                {
                    if (_loaiVatTuDmLoaiVatTu.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnIdLoaiVatTuChanging(value);
                    SendPropertyChanging("IdLoaiVatTu");
                    _idLoaiVatTu = value;
                    SendPropertyChanged("IdLoaiVatTu");
                    OnIdLoaiVatTuChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private int _soLuong;

        /// <summary>
        /// Gets or sets the SoLuong column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "SoLuong", Storage = "_soLuong", DbType = "int NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 4)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public int SoLuong
        {
            get { return _soLuong; }
            set
            {
                if (_soLuong != value)
                {
                    OnSoLuongChanging(value);
                    SendPropertyChanging("SoLuong");
                    _soLuong = value;
                    SendPropertyChanged("SoLuong");
                    OnSoLuongChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.DateTime _ngayTaoDate;

        /// <summary>
        /// Gets or sets the NgayTaoDate column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "NgayTaoDate", Storage = "_ngayTaoDate", DbType = "date NOT NULL", CanBeNull = false)]
        [System.Runtime.Serialization.DataMember(Order = 5)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.DateTime NgayTaoDate
        {
            get { return _ngayTaoDate; }
            set
            {
                if (_ngayTaoDate != value)
                {
                    OnNgayTaoDateChanging(value);
                    SendPropertyChanging("NgayTaoDate");
                    _ngayTaoDate = value;
                    SendPropertyChanged("NgayTaoDate");
                    OnNgayTaoDateChanged();
                }
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private string _chuThich;

        /// <summary>
        /// Gets or sets the ChuThich column value.
        /// </summary>
        [System.Data.Linq.Mapping.Column(Name = "ChuThich", Storage = "_chuThich", DbType = "nvarchar(300)")]
        [System.ComponentModel.DataAnnotations.StringLength(300)]
        [System.Runtime.Serialization.DataMember(Order = 6)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public string ChuThich
        {
            get { return _chuThich; }
            set
            {
                if (_chuThich != value)
                {
                    OnChuThichChanging(value);
                    SendPropertyChanging("ChuThich");
                    _chuThich = value;
                    SendPropertyChanged("ChuThich");
                    OnChuThichChanged();
                }
            }
        }
        #endregion

        #region Association Mapped Properties

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<DmLoaiVatTu> _loaiVatTuDmLoaiVatTu;

        /// <summary>
        /// Gets or sets the <see cref="DmLoaiVatTu"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "DmLoaiVatTu_KhPhieuXuatCt", Storage = "_loaiVatTuDmLoaiVatTu", ThisKey = "IdLoaiVatTu", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 7, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public DmLoaiVatTu LoaiVatTuDmLoaiVatTu
        {
            get { return (serializing && !_loaiVatTuDmLoaiVatTu.HasLoadedOrAssignedValue) ? null : _loaiVatTuDmLoaiVatTu.Entity; }
            set
            {
                DmLoaiVatTu previousValue = _loaiVatTuDmLoaiVatTu.Entity;
                if (previousValue != value || _loaiVatTuDmLoaiVatTu.HasLoadedOrAssignedValue == false)
                {
                    OnLoaiVatTuDmLoaiVatTuChanging(value);
                    SendPropertyChanging("LoaiVatTuDmLoaiVatTu");
                    if (previousValue != null)
                    {
                        _loaiVatTuDmLoaiVatTu.Entity = null;
                        previousValue.LoaiVatTuKhPhieuXuatCtList.Remove(this);
                    }
                    _loaiVatTuDmLoaiVatTu.Entity = value;
                    if (value != null)
                    {
                        value.LoaiVatTuKhPhieuXuatCtList.Add(this);
                        _idLoaiVatTu = value.Id;
                    }
                    else
                    {
                        _idLoaiVatTu = default(System.Guid);
                    }
                    SendPropertyChanged("LoaiVatTuDmLoaiVatTu");
                    OnLoaiVatTuDmLoaiVatTuChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntityRef<KhPhieuXuat> _phieuXuatKhPhieuXuat;

        /// <summary>
        /// Gets or sets the <see cref="KhPhieuXuat"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "KhPhieuXuat_KhPhieuXuatCt", Storage = "_phieuXuatKhPhieuXuat", ThisKey = "IdPhieuXuat", OtherKey = "Id", IsForeignKey = true)]
        [System.Runtime.Serialization.DataMember(Order = 8, EmitDefaultValue = false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhPhieuXuat PhieuXuatKhPhieuXuat
        {
            get { return (serializing && !_phieuXuatKhPhieuXuat.HasLoadedOrAssignedValue) ? null : _phieuXuatKhPhieuXuat.Entity; }
            set
            {
                KhPhieuXuat previousValue = _phieuXuatKhPhieuXuat.Entity;
                if (previousValue != value || _phieuXuatKhPhieuXuat.HasLoadedOrAssignedValue == false)
                {
                    OnPhieuXuatKhPhieuXuatChanging(value);
                    SendPropertyChanging("PhieuXuatKhPhieuXuat");
                    if (previousValue != null)
                    {
                        _phieuXuatKhPhieuXuat.Entity = null;
                        previousValue.PhieuXuatKhPhieuXuatCtList.Remove(this);
                    }
                    _phieuXuatKhPhieuXuat.Entity = value;
                    if (value != null)
                    {
                        value.PhieuXuatKhPhieuXuatCtList.Add(this);
                        _idPhieuXuat = value.Id;
                    }
                    else
                    {
                        _idPhieuXuat = default(System.Guid);
                    }
                    SendPropertyChanged("PhieuXuatKhPhieuXuat");
                    OnPhieuXuatKhPhieuXuatChanged();
                }
            }
        }
        
        
        

        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private System.Data.Linq.EntitySet<KhPhieuXuatSp> _phieuXuatCtKhPhieuXuatSpList;

        /// <summary>
        /// Gets or sets the <see cref="KhPhieuXuatSp"/> association.
        /// </summary>
        [System.Data.Linq.Mapping.Association(Name = "KhPhieuXuatCt_KhPhieuXuatSp", Storage = "_phieuXuatCtKhPhieuXuatSpList", ThisKey = "Id", OtherKey = "IdPhieuXuatCt")]
        [System.Runtime.Serialization.DataMember(Order=9, EmitDefaultValue=false)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public System.Data.Linq.EntitySet<KhPhieuXuatSp> PhieuXuatCtKhPhieuXuatSpList
        {
            get { return (serializing && !_phieuXuatCtKhPhieuXuatSpList.HasLoadedOrAssignedValues) ? null : _phieuXuatCtKhPhieuXuatSpList; }
            set { _phieuXuatCtKhPhieuXuatSpList.Assign(value); }
        }
        
        

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void OnPhieuXuatCtKhPhieuXuatSpListAdd(KhPhieuXuatSp entity)
        {
            SendPropertyChanging(null);
            entity.PhieuXuatCtKhPhieuXuatCt = this;
            SendPropertyChanged(null);
        }

        [System.Diagnostics.DebuggerNonUserCode]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private void OnPhieuXuatCtKhPhieuXuatSpListRemove(KhPhieuXuatSp entity)
        {
            SendPropertyChanging(null);
            entity.PhieuXuatCtKhPhieuXuatCt = null;
            SendPropertyChanged(null);
        }
        #endregion

        #region Extensibility Method Definitions
        /// <summary>Called by the static constructor to add shared rules.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        static partial void AddSharedRules();
        /// <summary>Called when this instance is loaded.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnCreated();
        /// <summary>Called when <see cref="Id"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdChanging(System.Guid value);
        /// <summary>Called after <see cref="Id"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdChanged();
        /// <summary>Called when <see cref="IdPhieuXuat"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdPhieuXuatChanging(System.Guid value);
        /// <summary>Called after <see cref="IdPhieuXuat"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdPhieuXuatChanged();
        /// <summary>Called when <see cref="IdLoaiVatTu"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdLoaiVatTuChanging(System.Guid value);
        /// <summary>Called after <see cref="IdLoaiVatTu"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnIdLoaiVatTuChanged();
        /// <summary>Called when <see cref="SoLuong"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnSoLuongChanging(int value);
        /// <summary>Called after <see cref="SoLuong"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnSoLuongChanged();
        /// <summary>Called when <see cref="NgayTaoDate"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnNgayTaoDateChanging(System.DateTime value);
        /// <summary>Called after <see cref="NgayTaoDate"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnNgayTaoDateChanged();
        /// <summary>Called when <see cref="ChuThich"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChuThichChanging(string value);
        /// <summary>Called after <see cref="ChuThich"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnChuThichChanged();
        /// <summary>Called when <see cref="LoaiVatTuDmLoaiVatTu"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaiVatTuDmLoaiVatTuChanging(DmLoaiVatTu value);
        /// <summary>Called after <see cref="LoaiVatTuDmLoaiVatTu"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnLoaiVatTuDmLoaiVatTuChanged();
        /// <summary>Called when <see cref="PhieuXuatKhPhieuXuat"/> is changing.</summary>
        /// <param name="value">The new value.</param>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnPhieuXuatKhPhieuXuatChanging(KhPhieuXuat value);
        /// <summary>Called after <see cref="PhieuXuatKhPhieuXuat"/> has Changed.</summary>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        partial void OnPhieuXuatKhPhieuXuatChanged();

        #endregion

        #region Serialization
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        private bool serializing;

        /// <summary>
        /// Called when serializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerializing(System.Runtime.Serialization.StreamingContext context) {
            serializing = true;
        }

        /// <summary>
        /// Called when serialized.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnSerialized]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnSerialized(System.Runtime.Serialization.StreamingContext context) {
            serializing = false;
        }

        /// <summary>
        /// Called when deserializing.
        /// </summary>
        /// <param name="context">The <see cref="System.Runtime.Serialization.StreamingContext"/> for the serialization.</param>
        [System.Runtime.Serialization.OnDeserializing]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public void OnDeserializing(System.Runtime.Serialization.StreamingContext context) {
            Initialize();
        }

        /// <summary>
        /// Deserializes an instance of <see cref="KhPhieuXuatCt"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="KhPhieuXuatCt"/> instance.</param>
        /// <returns>An instance of <see cref="KhPhieuXuatCt"/> that is deserialized from the XML string.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static KhPhieuXuatCt FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(KhPhieuXuatCt));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as KhPhieuXuatCt;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="KhPhieuXuatCt"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="KhPhieuXuatCt"/> instance.</param>
        /// <returns>An instance of <see cref="KhPhieuXuatCt"/> that is deserialized from the byte array.</returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public static KhPhieuXuatCt FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(KhPhieuXuatCt));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as KhPhieuXuatCt;
            }
        }
        
        #endregion

        #region Clone
        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        object ICloneable.Clone()
        {
            var serializer = new System.Runtime.Serialization.DataContractSerializer(GetType());
            using (var ms = new System.IO.MemoryStream())
            {
                serializer.WriteObject(ms, this);
                ms.Position = 0;
                return serializer.ReadObject(ms);
            }
        }

        /// <summary>
        /// Creates a new object that is a copy of the current instance.
        /// </summary>
        /// <returns>
        /// A new object that is a copy of this instance.
        /// </returns>
        /// <remarks>
        /// Only loaded <see cref="T:System.Data.Linq.EntityRef`1"/> and <see cref="T:System.Data.Linq.EntitySet`1" /> child accessions will be cloned.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public KhPhieuXuatCt Clone()
        {
            return (KhPhieuXuatCt)((ICloneable)this).Clone();
        }
        #endregion

        #region Detach Methods
        /// <summary>
        /// Detach this instance from the <see cref="System.Data.Linq.DataContext"/>.
        /// </summary>
        /// <remarks>
        /// Detaching the entity will stop all lazy loading and allow it to be added to another <see cref="System.Data.Linq.DataContext"/>.
        /// </remarks>
        [System.CodeDom.Compiler.GeneratedCode("CodeSmith", "6.0.0.0")]
        public override void Detach()
        {
            if (!IsAttached())
                return;

            base.Detach();
            _loaiVatTuDmLoaiVatTu = Detach(_loaiVatTuDmLoaiVatTu);
            _phieuXuatKhPhieuXuat = Detach(_phieuXuatKhPhieuXuat);
            _phieuXuatCtKhPhieuXuatSpList = Detach(_phieuXuatCtKhPhieuXuatSpList, OnPhieuXuatCtKhPhieuXuatSpListAdd, OnPhieuXuatCtKhPhieuXuatSpListRemove);
        }
        #endregion
    }
}
#pragma warning restore 1591
#pragma warning restore 0414
