using System;
using System.ComponentModel;

namespace SMSSC.Entities
{
	/// <summary>
	///		The data structure representation of the 'MessageTemplate' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMessageTemplate 
	{
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "MessageTemplate"</remarks>
		System.Int32 Id { get; set; }
				
		
		
		/// <summary>
		/// Title : 
		/// </summary>
		System.String  Title  { get; set; }
		
		/// <summary>
		/// ContentText : 
		/// </summary>
		System.String  ContentText  { get; set; }
		
		/// <summary>
		/// Status : 
		/// </summary>
		System.Int32  Status  { get; set; }
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		System.DateTime  CreatedDate  { get; set; }
		
		/// <summary>
		/// Note : 
		/// </summary>
		System.String  Note  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		

	}
}


