
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file MessageHistory.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using SMSSC.Entities.Validation;
#endregion

namespace SMSSC.Entities
{
	///<summary>An object representation of the 'MessageHistory' table. [No description found the database]</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class MessageHistoryBase : EntityBase, IMessageHistory, IEntityId<MessageHistoryKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private MessageHistoryEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private MessageHistoryEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MessageHistoryEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<MessageHistory> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MessageHistoryEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MessageHistoryEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MessageHistoryBase"/> instance.
		///</summary>
		public MessageHistoryBase()
		{
			this.entityData = new MessageHistoryEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MessageHistoryBase"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_messageType"></param>
		///<param name="_fromPhoneNumber"></param>
		///<param name="_toPhoneNumber"></param>
		///<param name="_contentText"></param>
		///<param name="_status"></param>
		///<param name="_createdDate"></param>
		///<param name="_sentDate"></param>
		///<param name="_note"></param>
		public MessageHistoryBase(System.Guid _id, System.Int32 _messageType, System.String _fromPhoneNumber, 
			System.String _toPhoneNumber, System.String _contentText, System.Int32 _status, 
			System.DateTime _createdDate, System.DateTime? _sentDate, System.String _note)
		{
			this.entityData = new MessageHistoryEntityData();
			this.backupData = null;

			this.Id = _id;
			this.MessageType = _messageType;
			this.FromPhoneNumber = _fromPhoneNumber;
			this.ToPhoneNumber = _toPhoneNumber;
			this.ContentText = _contentText;
			this.Status = _status;
			this.CreatedDate = _createdDate;
			this.SentDate = _sentDate;
			this.Note = _note;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="MessageHistory"/> instance.
		///</summary>
		///<param name="_id"></param>
		///<param name="_messageType"></param>
		///<param name="_fromPhoneNumber"></param>
		///<param name="_toPhoneNumber"></param>
		///<param name="_contentText"></param>
		///<param name="_status"></param>
		///<param name="_createdDate"></param>
		///<param name="_sentDate"></param>
		///<param name="_note"></param>
		public static MessageHistory CreateMessageHistory(System.Guid _id, System.Int32 _messageType, System.String _fromPhoneNumber, 
			System.String _toPhoneNumber, System.String _contentText, System.Int32 _status, 
			System.DateTime _createdDate, System.DateTime? _sentDate, System.String _note)
		{
			MessageHistory newMessageHistory = new MessageHistory();
			newMessageHistory.Id = _id;
			newMessageHistory.MessageType = _messageType;
			newMessageHistory.FromPhoneNumber = _fromPhoneNumber;
			newMessageHistory.ToPhoneNumber = _toPhoneNumber;
			newMessageHistory.ContentText = _contentText;
			newMessageHistory.Status = _status;
			newMessageHistory.CreatedDate = _createdDate;
			newMessageHistory.SentDate = _sentDate;
			newMessageHistory.Note = _note;
			return newMessageHistory;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the Id property. 
		///		
		/// </summary>
		/// <value>This type is uniqueidentifier.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Id is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Guid Id
		{
			get
			{
				return this.entityData.Id; 
			}
			
			set
			{
				if (this.entityData.Id == value)
					return;
				
                OnPropertyChanging("Id");                    
				OnColumnChanging(MessageHistoryColumn.Id, this.entityData.Id);
				this.entityData.Id = value;
				this.EntityId.Id = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.Id, this.entityData.Id);
				OnPropertyChanged("Id");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the Id property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the Id property.</remarks>
		/// <value>This type is uniqueidentifier</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Guid OriginalId
		{
			get { return this.entityData.OriginalId; }
			set { this.entityData.OriginalId = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the MessageType property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "MessageType is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 MessageType
		{
			get
			{
				return this.entityData.MessageType; 
			}
			
			set
			{
				if (this.entityData.MessageType == value)
					return;
				
                OnPropertyChanging("MessageType");                    
				OnColumnChanging(MessageHistoryColumn.MessageType, this.entityData.MessageType);
				this.entityData.MessageType = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.MessageType, this.entityData.MessageType);
				OnPropertyChanged("MessageType");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the FromPhoneNumber property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "FromPhoneNumber is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 15)]
		public virtual System.String FromPhoneNumber
		{
			get
			{
				return this.entityData.FromPhoneNumber; 
			}
			
			set
			{
				if (this.entityData.FromPhoneNumber == value)
					return;
				
                OnPropertyChanging("FromPhoneNumber");                    
				OnColumnChanging(MessageHistoryColumn.FromPhoneNumber, this.entityData.FromPhoneNumber);
				this.entityData.FromPhoneNumber = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.FromPhoneNumber, this.entityData.FromPhoneNumber);
				OnPropertyChanged("FromPhoneNumber");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ToPhoneNumber property. 
		///		
		/// </summary>
		/// <value>This type is varchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "ToPhoneNumber is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 15)]
		public virtual System.String ToPhoneNumber
		{
			get
			{
				return this.entityData.ToPhoneNumber; 
			}
			
			set
			{
				if (this.entityData.ToPhoneNumber == value)
					return;
				
                OnPropertyChanging("ToPhoneNumber");                    
				OnColumnChanging(MessageHistoryColumn.ToPhoneNumber, this.entityData.ToPhoneNumber);
				this.entityData.ToPhoneNumber = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.ToPhoneNumber, this.entityData.ToPhoneNumber);
				OnPropertyChanged("ToPhoneNumber");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ContentText property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		[Required(ErrorMessage = "ContentText is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 180)]
		public override System.String ContentText
		{
			get
			{
				return this.entityData.ContentText; 
			}
			
			set
			{
				if (this.entityData.ContentText == value)
					return;
				
                OnPropertyChanging("ContentText");                    
				OnColumnChanging(MessageHistoryColumn.ContentText, this.entityData.ContentText);
				this.entityData.ContentText = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.ContentText, this.entityData.ContentText);
				OnPropertyChanged("ContentText");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Status property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "Status is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.Int32 Status
		{
			get
			{
				return this.entityData.Status; 
			}
			
			set
			{
				if (this.entityData.Status == value)
					return;
				
                OnPropertyChanging("Status");                    
				OnColumnChanging(MessageHistoryColumn.Status, this.entityData.Status);
				this.entityData.Status = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.Status, this.entityData.Status);
				OnPropertyChanged("Status");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CreatedDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		[Required(ErrorMessage = "CreatedDate is required")]




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public override System.DateTime CreatedDate
		{
			get
			{
				return this.entityData.CreatedDate; 
			}
			
			set
			{
				if (this.entityData.CreatedDate == value)
					return;
				
                OnPropertyChanging("CreatedDate");                    
				OnColumnChanging(MessageHistoryColumn.CreatedDate, this.entityData.CreatedDate);
				this.entityData.CreatedDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.CreatedDate, this.entityData.CreatedDate);
				OnPropertyChanged("CreatedDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the SentDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsSentDateNull() and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? SentDate
		{
			get
			{
				return this.entityData.SentDate; 
			}
			
			set
			{
				if (this.entityData.SentDate == value)
					return;
				
                OnPropertyChanging("SentDate");                    
				OnColumnChanging(MessageHistoryColumn.SentDate, this.entityData.SentDate);
				this.entityData.SentDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.SentDate, this.entityData.SentDate);
				OnPropertyChanged("SentDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Note property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 300)]
		public override System.String Note
		{
			get
			{
				return this.entityData.Note; 
			}
			
			set
			{
				if (this.entityData.Note == value)
					return;
				
                OnPropertyChanging("Note");                    
				OnColumnChanging(MessageHistoryColumn.Note, this.entityData.Note);
				this.entityData.Note = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MessageHistoryColumn.Note, this.entityData.Note);
				OnPropertyChanged("Note");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
        
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("FromPhoneNumber", "From Phone Number"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("FromPhoneNumber", "From Phone Number", 15));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("ToPhoneNumber", "To Phone Number"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ToPhoneNumber", "To Phone Number", 15));
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("ContentText", "Content Text"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ContentText", "Content Text", 180));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Note", "Note", 300));
		}
   		#endregion
        
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "MessageHistory"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"Id", "MessageType", "FromPhoneNumber", "ToPhoneNumber", "ContentText", "Status", "CreatedDate", "SentDate", "Note"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MessageHistoryEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (MessageHistory) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<MessageHistory>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as MessageHistory);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed MessageHistory Entity 
		///</summary>
		protected virtual MessageHistory Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			MessageHistory copy = new MessageHistory();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.Id = this.Id;
					copy.OriginalId = this.OriginalId;
				copy.MessageType = this.MessageType;
				copy.FromPhoneNumber = this.FromPhoneNumber;
				copy.ToPhoneNumber = this.ToPhoneNumber;
				copy.ContentText = this.ContentText;
				copy.Status = this.Status;
				copy.CreatedDate = this.CreatedDate;
				copy.SentDate = this.SentDate;
				copy.Note = this.Note;
			
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed MessageHistory Entity 
		///</summary>
		public virtual MessageHistory Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed MessageHistory Entity which is a deep copy of the current entity.
		///</summary>
		public virtual MessageHistory DeepCopy()
		{
			return EntityHelper.Clone<MessageHistory>(this as MessageHistory);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MessageHistoryEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new MessageHistoryEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MessageHistoryEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MessageHistoryColumn column)
		{
			switch(column)
			{
					case MessageHistoryColumn.Id:
					return entityData.Id != _originalData.Id;
					case MessageHistoryColumn.MessageType:
					return entityData.MessageType != _originalData.MessageType;
					case MessageHistoryColumn.FromPhoneNumber:
					return entityData.FromPhoneNumber != _originalData.FromPhoneNumber;
					case MessageHistoryColumn.ToPhoneNumber:
					return entityData.ToPhoneNumber != _originalData.ToPhoneNumber;
					case MessageHistoryColumn.ContentText:
					return entityData.ContentText != _originalData.ContentText;
					case MessageHistoryColumn.Status:
					return entityData.Status != _originalData.Status;
					case MessageHistoryColumn.CreatedDate:
					return entityData.CreatedDate != _originalData.CreatedDate;
					case MessageHistoryColumn.SentDate:
					return entityData.SentDate != _originalData.SentDate;
					case MessageHistoryColumn.Note:
					return entityData.Note != _originalData.Note;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< MessageHistoryColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.Id != _originalData.Id;
			result = result || entityData.MessageType != _originalData.MessageType;
			result = result || entityData.FromPhoneNumber != _originalData.FromPhoneNumber;
			result = result || entityData.ToPhoneNumber != _originalData.ToPhoneNumber;
			result = result || entityData.ContentText != _originalData.ContentText;
			result = result || entityData.Status != _originalData.Status;
			result = result || entityData.CreatedDate != _originalData.CreatedDate;
			result = result || entityData.SentDate != _originalData.SentDate;
			result = result || entityData.Note != _originalData.Note;
			return result;
		}	
		
		///<summary>
		///  Returns a MessageHistory Entity with the original data.
		///</summary>
		public MessageHistory GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMessageHistory(
				_originalData.Id,
				_originalData.MessageType,
				_originalData.FromPhoneNumber,
				_originalData.ToPhoneNumber,
				_originalData.ContentText,
				_originalData.Status,
				_originalData.CreatedDate,
				_originalData.SentDate,
				_originalData.Note
				);
				
			return (MessageHistory)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MessageHistoryBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MessageHistoryBase)
				return ValueEquals(this, (MessageHistoryBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MessageHistoryBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.Id.GetHashCode() ^ 
					this.MessageType.GetHashCode() ^ 
					this.FromPhoneNumber.GetHashCode() ^ 
					this.ToPhoneNumber.GetHashCode() ^ 
					this.ContentText.GetHashCode() ^ 
					this.Status.GetHashCode() ^ 
					this.CreatedDate.GetHashCode() ^ 
					((this.SentDate == null) ? string.Empty : this.SentDate.ToString()).GetHashCode() ^ 
					((this.Note == null) ? string.Empty : this.Note.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MessageHistoryBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MessageHistoryBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MessageHistoryBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MessageHistoryBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MessageHistoryBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MessageHistoryBase Object1, MessageHistoryBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.Id != Object2.Id)
				equal = false;
			if (Object1.MessageType != Object2.MessageType)
				equal = false;
			if (Object1.FromPhoneNumber != Object2.FromPhoneNumber)
				equal = false;
			if (Object1.ToPhoneNumber != Object2.ToPhoneNumber)
				equal = false;
			if (Object1.ContentText != Object2.ContentText)
				equal = false;
			if (Object1.Status != Object2.Status)
				equal = false;
			if (Object1.CreatedDate != Object2.CreatedDate)
				equal = false;
			if ( Object1.SentDate != null && Object2.SentDate != null )
			{
				if (Object1.SentDate != Object2.SentDate)
					equal = false;
			}
			else if (Object1.SentDate == null ^ Object2.SentDate == null )
			{
				equal = false;
			}
			if ( Object1.Note != null && Object2.Note != null )
			{
				if (Object1.Note != Object2.Note)
					equal = false;
			}
			else if (Object1.Note == null ^ Object2.Note == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MessageHistoryBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MessageHistoryComparer GetComparer()
        {
            return new MessageHistoryComparer();
        }
        */

        // Comparer delegates back to MessageHistory
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(MessageHistory rhs, MessageHistoryColumn which)
        {
            switch (which)
            {
            	
            	
            	case MessageHistoryColumn.Id:
            		return this.Id.CompareTo(rhs.Id);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.MessageType:
            		return this.MessageType.CompareTo(rhs.MessageType);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.FromPhoneNumber:
            		return this.FromPhoneNumber.CompareTo(rhs.FromPhoneNumber);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.ToPhoneNumber:
            		return this.ToPhoneNumber.CompareTo(rhs.ToPhoneNumber);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.ContentText:
            		return this.ContentText.CompareTo(rhs.ContentText);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.Status:
            		return this.Status.CompareTo(rhs.Status);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.CreatedDate:
            		return this.CreatedDate.CompareTo(rhs.CreatedDate);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.SentDate:
            		return this.SentDate.Value.CompareTo(rhs.SentDate.Value);
            		
            		                 
            	
            	
            	case MessageHistoryColumn.Note:
            		return this.Note.CompareTo(rhs.Note);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MessageHistoryKey> Members
		
		// member variable for the EntityId property
		private MessageHistoryKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MessageHistoryKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MessageHistoryKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("MessageHistory")
					.Append("|").Append( this.Id.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- Id: {0}{9}- MessageType: {1}{9}- FromPhoneNumber: {2}{9}- ToPhoneNumber: {3}{9}- ContentText: {4}{9}- Status: {5}{9}- CreatedDate: {6}{9}- SentDate: {7}{9}- Note: {8}{9}{11}", 
				this.Id,
				this.MessageType,
				this.FromPhoneNumber,
				this.ToPhoneNumber,
				this.ContentText,
				this.Status,
				this.CreatedDate,
				(this.SentDate == null) ? string.Empty : this.SentDate.ToString(),
				(this.Note == null) ? string.Empty : this.Note.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'MessageHistory' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class MessageHistoryEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Id : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "MessageHistory"</remarks>
		public System.Guid Id;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Guid OriginalId;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// MessageType : 
		/// </summary>
		public System.Int32 MessageType = (int)0;
		
		/// <summary>
		/// FromPhoneNumber : 
		/// </summary>
		public System.String FromPhoneNumber = string.Empty;
		
		/// <summary>
		/// ToPhoneNumber : 
		/// </summary>
		public System.String ToPhoneNumber = string.Empty;
		
		/// <summary>
		/// ContentText : 
		/// </summary>
		public System.String ContentText = string.Empty;
		
		/// <summary>
		/// Status : 
		/// </summary>
		public System.Int32 Status = (int)0;
		
		/// <summary>
		/// CreatedDate : 
		/// </summary>
		public System.DateTime CreatedDate = DateTime.MinValue;
		
		/// <summary>
		/// SentDate : 
		/// </summary>
		public System.DateTime? SentDate = null;
		
		/// <summary>
		/// Note : 
		/// </summary>
		public System.String Note = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MessageHistoryEntityData _tmp = new MessageHistoryEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.MessageType = this.MessageType;
			_tmp.FromPhoneNumber = this.FromPhoneNumber;
			_tmp.ToPhoneNumber = this.ToPhoneNumber;
			_tmp.ContentText = this.ContentText;
			_tmp.Status = this.Status;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.SentDate = this.SentDate;
			_tmp.Note = this.Note;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MessageHistoryEntityData _tmp = new MessageHistoryEntityData();
						
			_tmp.Id = this.Id;
			_tmp.OriginalId = this.OriginalId;
			
			_tmp.MessageType = this.MessageType;
			_tmp.FromPhoneNumber = this.FromPhoneNumber;
			_tmp.ToPhoneNumber = this.ToPhoneNumber;
			_tmp.ContentText = this.ContentText;
			_tmp.Status = this.Status;
			_tmp.CreatedDate = this.CreatedDate;
			_tmp.SentDate = this.SentDate;
			_tmp.Note = this.Note;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MessageHistoryColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MessageHistoryColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MessageHistoryColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MessageHistoryColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MessageHistoryColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MessageHistoryColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				MessageHistoryEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MessageHistoryEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MessageHistoryColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MessageHistoryColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MessageHistoryEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MessageHistoryEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
	} // End Class
	
	#region MessageHistoryEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="MessageHistory"/> object.
	/// </remarks>
	public class MessageHistoryEventArgs : System.EventArgs
	{
		private MessageHistoryColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MessageHistoryEventArgs class.
		///</summary>
		public MessageHistoryEventArgs(MessageHistoryColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MessageHistoryEventArgs class.
		///</summary>
		public MessageHistoryEventArgs(MessageHistoryColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MessageHistoryColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MessageHistoryColumn" />
		public MessageHistoryColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>Define a delegate for all MessageHistory related events.</summary>
	public delegate void MessageHistoryEventHandler(object sender, MessageHistoryEventArgs e);
	
	#region MessageHistoryComparer
		
	/// <summary>Strongly Typed IComparer</summary>
	public class MessageHistoryComparer : System.Collections.Generic.IComparer<MessageHistory>
	{
		MessageHistoryColumn whichComparison;
		
		/// <summary>Initializes a new instance of the <see cref="T:MessageHistoryComparer"/> class.</summary>
		public MessageHistoryComparer()
        {            
        }               
        
        /// <summary>Initializes a new instance of the <see cref="T:MessageHistoryComparer"/> class.</summary>
        /// <param name="column">The column to sort on.</param>
        public MessageHistoryComparer(MessageHistoryColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>Determines whether the specified <see cref="MessageHistory"/> instances are considered equal.</summary>
        /// <param name="a">The first <see cref="MessageHistory"/> to compare.</param>
        /// <param name="b">The second <c>MessageHistory</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(MessageHistory a, MessageHistory b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>Gets the hash code of the specified entity.</summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(MessageHistory entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.</summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(MessageHistory a, MessageHistory b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>Gets or sets the column that will be used for comparison.</summary>
        /// <value>The comparison column.</value>
        public MessageHistoryColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MessageHistoryKey Class

	/// <summary>Wraps the unique identifier values for the <see cref="MessageHistory"/> object.</summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MessageHistoryKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>Initializes a new instance of the MessageHistoryKey class.</summary>
		public MessageHistoryKey()
		{
		}
		
		/// <summary>Initializes a new instance of the MessageHistoryKey class.</summary>
		public MessageHistoryKey(MessageHistoryBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Id = entity.Id;
			}

			#endregion
		}
		
		/// <summary>Initializes a new instance of the MessageHistoryKey class.</summary>
		public MessageHistoryKey(System.Guid _id)
		{
			#region Init Properties

			this.Id = _id;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MessageHistoryBase _entity;
		
		/// <summary>Gets or sets the Entity property.</summary>
		public MessageHistoryBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Id property
		private System.Guid _id;
		
		/// <summary>Gets or sets the Id property.</summary>
		public System.Guid Id
		{
			get 
            { 
                return _id; 
            }
			set
			{
				if ( this.Entity != null )
					this.Entity.Id = value;
				
				_id = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>Reads values from the supplied <see cref="IDictionary"/> object into properties of the current object.</summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Id = ( values["Id"] != null ) ? (System.Guid) EntityUtil.ChangeType(values["Id"], typeof(System.Guid)) : Guid.Empty;
			}

			#endregion
		}

		/// <summary>Creates a new <see cref="IDictionary"/> object and populates it with the property values of the current object.</summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Id", Id);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>Returns a String that represents the current object.</summary>
		public override string ToString()
		{
			return String.Format("Id: {0}{1}",Id,System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MessageHistoryColumn Enum
	
	/// <summary>Enumerate the MessageHistory columns.</summary>
	[Serializable]
	public enum MessageHistoryColumn : int
	{
        /// <summary>Id : </summary>
		[EnumTextValue("Id")]
		[ColumnEnum("Id", typeof(System.Guid), System.Data.DbType.Guid, true, false, false)]
		Id = 1,
        /// <summary>MessageType : </summary>
		[EnumTextValue("MessageType")]
		[ColumnEnum("MessageType", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		MessageType = 2,
        /// <summary>FromPhoneNumber : </summary>
		[EnumTextValue("FromPhoneNumber")]
		[ColumnEnum("FromPhoneNumber", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 15)]
		FromPhoneNumber = 3,
        /// <summary>ToPhoneNumber : </summary>
		[EnumTextValue("ToPhoneNumber")]
		[ColumnEnum("ToPhoneNumber", typeof(System.String), System.Data.DbType.AnsiString, false, false, false, 15)]
		ToPhoneNumber = 4,
        /// <summary>ContentText : </summary>
		[EnumTextValue("ContentText")]
		[ColumnEnum("ContentText", typeof(System.String), System.Data.DbType.String, false, false, false, 180)]
		ContentText = 5,
        /// <summary>Status : </summary>
		[EnumTextValue("Status")]
		[ColumnEnum("Status", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Status = 6,
        /// <summary>CreatedDate : </summary>
		[EnumTextValue("CreatedDate")]
		[ColumnEnum("CreatedDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		CreatedDate = 7,
        /// <summary>SentDate : </summary>
		[EnumTextValue("SentDate")]
		[ColumnEnum("SentDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		SentDate = 8,
        /// <summary>Note : </summary>
		[EnumTextValue("Note")]
		[ColumnEnum("Note", typeof(System.String), System.Data.DbType.String, false, false, true, 300)]
		Note = 9
	}//End enum

	#endregion MessageHistoryColumn Enum

} // end namespace
